name: zuccante_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  http: ^0.13.5
  flutter_html: ^2.2.1
  url_launcher: ^6.1.10
  dio: ^5.0.1
  html: ^0.15.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.jpg"
  
flutter:
  uses-material-design: true
  assets: 
      -  assets/logo.jpg
  